import AuthProvider from '@/providers/AuthProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <AuthProvider>
        <AntdRegistry>
        <Toaster richColors />
          <div className='mx-auto min-h-screen bg-gray-50'>
          {children}
          </div>
        </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
